"""v3_userstatus_landing

Revision ID: cf5b71f0e3bc
Revises: 95d76c5dbb2f
Create Date: 2026-07-19 13:26:57.370108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cf5b71f0e3bc'
down_revision: Union[str, Sequence[str], None] = '95d76c5dbb2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cidade', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('membro_igreja', sa.Boolean(), nullable=False),
    sa.Column('nome_igreja', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('denominacao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mensagem', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observacoes_admin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestor_criado_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_email'), ['email'], unique=False)

    op.create_table('siteconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('siteconfig', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_siteconfig_chave'), ['chave'], unique=True)

    op.create_table('testemunho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cidade', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profissao_fe', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('texto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('foto_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mensagem', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('email_enviado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('metodo_pagamento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('referencia_externa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observacoes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_user_id'), ['user_id'], unique=False)

    op.create_table('paymenthistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('valor_pago', sa.Float(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('metodo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('referencia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('observacoes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paymenthistory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paymenthistory_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paymenthistory_user_id'), ['user_id'], unique=False)

    op.drop_table('turmamembro')
    op.drop_table('turma')
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.alter_column('last_activity',
               nullable=True)

    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'basico'"), nullable=False))
        batch_op.add_column(sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'rascunho'"), nullable=False))
        batch_op.add_column(sa.Column('proposto_por', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('aprovado_por', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('feedback_admin', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('prerequisite_study_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('created_at',
               nullable=True)
        batch_op.create_foreign_key(None, 'study', ['prerequisite_study_id'], ['id'])

    with op.batch_alter_table('studyassignment', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               nullable=True)

    with op.batch_alter_table('studyversion', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_completo', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('nome_base', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('data_nascimento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('sexo', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('profissao_fe', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('auto_descricao', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('escolaridade', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('cep', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('logradouro', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('complemento', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('bairro', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('cidade', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'suspenso'"), nullable=False))
        batch_op.add_column(sa.Column('status_reason', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('suspension_token', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('suspension_token_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_activity_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('supervisor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('meta_supervisores', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('meta_alunos', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('assinatura_ativa', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('data_vencimento', sa.Date(), nullable=True))
        batch_op.alter_column('created_at',
               nullable=True)
        batch_op.alter_column('updated_at',
               nullable=True)
        batch_op.create_index(batch_op.f('ix_user_cpf'), ['cpf'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['supervisor_id'], ['id'])
        batch_op.drop_column('nome')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('userresponse', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userresponse', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_cpf'))
        batch_op.alter_column('updated_at',
               nullable=False)
        batch_op.alter_column('created_at',
               nullable=False)
        batch_op.drop_column('data_vencimento')
        batch_op.drop_column('assinatura_ativa')
        batch_op.drop_column('meta_alunos')
        batch_op.drop_column('meta_supervisores')
        batch_op.drop_column('supervisor_id')
        batch_op.drop_column('last_activity_at')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('suspension_token_expires')
        batch_op.drop_column('suspension_token')
        batch_op.drop_column('status_reason')
        batch_op.drop_column('status')
        batch_op.drop_column('must_change_password')
        batch_op.drop_column('telefone')
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')
        batch_op.drop_column('bairro')
        batch_op.drop_column('complemento')
        batch_op.drop_column('numero')
        batch_op.drop_column('logradouro')
        batch_op.drop_column('cep')
        batch_op.drop_column('escolaridade')
        batch_op.drop_column('auto_descricao')
        batch_op.drop_column('profissao_fe')
        batch_op.drop_column('sexo')
        batch_op.drop_column('data_nascimento')
        batch_op.drop_column('cpf')
        batch_op.drop_column('nome_base')
        batch_op.drop_column('nome_completo')

    with op.batch_alter_table('studyversion', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               nullable=False)

    with op.batch_alter_table('studyassignment', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               nullable=False)

    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_at',
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('prerequisite_study_id')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('feedback_admin')
        batch_op.drop_column('aprovado_por')
        batch_op.drop_column('proposto_por')
        batch_op.drop_column('status')
        batch_op.drop_column('level')

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.alter_column('last_activity',
               nullable=False)

    op.create_table('turmamembro',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('turma_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_entrada', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data_saida', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], name=op.f('turmamembro_turma_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('turmamembro_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('turmamembro_pkey'))
    )
    op.create_table('turma',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gestor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('coordenador_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('study_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_inicio', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('data_fim', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['coordenador_id'], ['user.id'], name=op.f('turma_coordenador_id_fkey')),
    sa.ForeignKeyConstraint(['gestor_id'], ['user.id'], name=op.f('turma_gestor_id_fkey')),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], name=op.f('turma_study_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('turma_pkey'))
    )
    with op.batch_alter_table('paymenthistory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paymenthistory_user_id'))
        batch_op.drop_index(batch_op.f('ix_paymenthistory_subscription_id'))

    op.drop_table('paymenthistory')
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_user_id'))

    op.drop_table('subscription')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))

    op.drop_table('notification')
    op.drop_table('testemunho')
    with op.batch_alter_table('siteconfig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_siteconfig_chave'))

    op.drop_table('siteconfig')
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_email'))

    op.drop_table('lead')
    # ### end Alembic commands ###
